<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Git2_FB" Id="{81cefd2c-386d-43f6-a0ca-cadba983885b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Git2_FB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Git2_FB">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>