<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Git1_FB" Id="{123682b9-97ca-4f0b-a925-882227d14872}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Git1_FB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Git1_FB">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>